spring:
  data:
    mongodb:
      port: 27017
      authentication-database: ${AUTH_DB}
      username: ${USERNAME}
      password: ${PASSWORD}
      database: chatDB
  profiles:
    active: dev

logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://223.130.146.39:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  logging:
    level:
      com.eum.haetsal: debug
springdoc:
  api-docs:
    path: /chat-service/docs
  swagger-ui:
    path: /chat-service/docs/swagger-ui.html
openapi:
  service:
    # API Gateway 포트
    url: http://localhost:80
