spring:
  application:
    name: prod-eum-chat

  data:
    mongodb:
      host: ${DEV_MONGO_HOST}
      database: ${PROD_DB}

server:
  port: 8080

haetsal-url: ${PROD_HAETSAL_URL}

db-name: ${PROD_DB}