spring:
  data:
    mongodb:
      port: ${MONGO_PORT}
      authentication-database: ${AUTH_DB}
      username: ${USERNAME}
      password: ${PASSWORD}
  profiles:
    active: prod

logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  logging:
    level:
      com.eum.haetsal: debug
