spring:
  application:
    name: local-eum-chat

springdoc:
  api-docs:
    path: /chat-service/docs
  swagger-ui:
    path: /chat-service/docs/swagger-ui.html

openapi:
  service:
    # API Gateway 포트
    url: http://localhost:80

haetsal-url: ${DEV_HAETSAL_URL}

