spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: chatDB

logging:
  level:
    org:
      springframework: INFO

server:
  port: 8080