spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/eum?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: root
  data:
    mongodb:
      port: 27017
      database: demo-chat
      authentication-database: admin
      username: root
      password: root

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

server:
  port: 8000