spring:
  data:
    mongodb:
      port: 27017
      authentication-database: ${AUTH_DB}
      username: ${USERNAME}
      password: ${PASSWORD}
      database: chatDB
  profiles:
    active: local

logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://223.130.146.39:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  logging:
    level:
      com.eum.haetsal: debug