name: deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "temurin"

      - name: Build with Gradle
        run: |
          ./gradlew bootJar
        env:
          SPRING_PROFILES_ACTIVE: ${{ (github.event_name == 'push') && 'dev' || 'prod' }}

      - name: Docker build & push to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME_YSY }} -p ${{ secrets.DOCKER_PASSWORD_YSY }}
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          docker build -t ${{ secrets.DOCKER_REPO_CHAT }} .
          docker push ${{ secrets.DOCKER_REPO_CHAT }}
          else
            docker build -t ${{ secrets.DOCKER_REPO_DEV_CHAT }} .
            docker push ${{ secrets.DOCKER_REPO_DEV_CHAT }}
          fi

  deploy_to_dev:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_CHAT_HOST }}
          username: ${{ secrets.SSH_DEV_CHAT_USERNAME }}
          password: ${{ secrets.SSH_DEV_CHAT_PWD }}
          script: |
            docker pull ${{ secrets.DOCKER_REPO_DEV_CHAT }}
            cd dev-eum-chat
            echo "${{ secrets.DEV_CHAT_ENV }}" > .env
            docker-compose up --build -d
            docker image prune -f

  deploy_to_prod:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_CHAT_HOST }}
          username: ${{ secrets.SSH_CHAT_USERNAME }}
          password: ${{ secrets.SSH_CHAT_PWD }}
          script: |
            docker pull ${{ secrets.DOCKER_REPO_CHAT }}
            cd timepay-chat
            echo "${{ secrets.CHAT_ENV }}" > .env
            docker-compose up --build -d
            docker image prune -f